#stage1
FROM node:16 AS stage1

RUN mkdir /app

WORKDIR /app

ARG VERSION
ENV APP_VERSION=version.${BASE_VERSION:-v1}

COPY . .

RUN npm install

RUN npm run build --prod
#stage2

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*

COPY --from=stage1 /app/nginx/* /etc/nginx/conf.d/default.conf
COPY --from=stage1 /app/dist/e-county /usr/share/nginx/html
